apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2rui
spec:
  replicas: 1
  selector:
    matchLabels:
      name: v2rui
  template:
    metadata:
      labels:
        name: v2rui
    spec:
      restartPolicy: Always
      containers:
        - name: v2rui
          image: hongchenvpn/v2rui
          ports:
            - containerPort: 8080
            
---
apiVersion: v1
kind: Service
metadata:
  name: v2rui
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "v2rui"
    port: 8080
  selector:
    name: v2rui
